# -*- coding: utf-8 -*-
"""Day2 Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J9OQ-IbpHUqye3DhJrMEc58KKP7_xPNV
"""

#1st experiment with dictionary
mydict={"name":"sai","age":21,"location":"vijayawada"}
mydict

#2nd experiment with dictionary
bioData = {"name":"sai","age":21}
bioData.get("age")

#3rd experiment with dictionary-remove element
mydict={1:1,2:2,3:6,4:8,5:10,6:12}
mydict.pop(2)
print(mydict)

#4th experiment with dictionary
mydict={"english":90,"science":60}
mydict.get("science")

#5th experiment with dictionary
mydict={"key1":"earth","key2":"venus",}
print(mydict)

9